name: Build and Deploy to SSH

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Astro site
        run: npm run build

      - name: Deploy to SSH server
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          SOURCE: "dist/"
          TARGET: "/var/www/tinkersdamn"
          ARGS: "-avzr --delete --omit-dir-times --no-perms --exclude=art --exclude=mp3s --exclude=promo --exclude=setlists"
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            echo "Setting ownership to rslsync:rslsync"
            sudo chown -R rslsync:rslsync /var/www/tinkersdamn
            echo "Deployment completed successfully"
            ls -al /var/www/tinkersdamn
